### ISSUE TITLE
Multiple emits from actions$ observable has inconsistent behavior

### ISSUE THREAD

**Issue by kuhnroyal** [ngxs-labs/emitter#128] opened 2019-01-30 13:42 UTC
When I subscribe to the `actions$` observable and do multiple emits from the subscription, only the last one gets emitted, but multiple times.

```typescript
    actions$.pipe(
      // same happens with ofActionDispatched/Successful
      ofEmittableDispatched(CounterState.incrementAll),
      switchMap(() => this.count$.pipe(first())),
      tap((counter) => {
        console.log("increment all");
        this.counterValue.emit(counter.value + 1);
        this.counterValue1.emit(counter.value1 + 1);
        // only the last one gets dispatched, but 3 times
        // one can work around it with setTimout or some kind of delay() operator
        this.counterValue2.emit(counter.value2 + 1);
      })
    ).subscribe();
```

Stackblitz:
https://stackblitz.com/edit/ngxs-emitter-example-gtdn6p

**Comment by thvu** [comment] 2019-08-20 12:33
I think root cause is that `EmitterAction` having a `static` `type` field while it should be a class property. As it is static right now, setting it in `EmitStore` while dispatching actions might cause overriding the type for dispatched actions. That's why the last action always win.

**Comment by arturovt** [comment] 2019-08-26 21:33
@kuhnroyal it might be fixed by `2.0.0`, could you confirm?

**Comment by arturovt** [comment] 2019-08-29 14:56
Just checked your example on the stackblitz and it seems to be working. I will close this issue. If you meet the issue again just leave a message here and I'll reopen.

**Closed by arturovt** 2019-08-29 14:56 UTC

**Comment by misterpy** [comment] 2019-10-17 17:07
This still does not work. Please look https://github.com/ngxs-labs/emitter/issues/147#issuecomment-543271124
